import type { NextPage } from 'next';
import Head from 'next/head';
import LinkButton from '@app/client/components/LinkButton';
import Header from '@app/client/components/Header';
import Layout from '@app/client/components/Layout';
import styles from './styles.module.scss';

const Home: NextPage = () => {
  return (
    <Layout>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Header />
        <main className={styles.main}>
          <div className={styles.introContainer}>
            <h2 className={styles.introTitle}>Привіт!</h2>
            <p className={styles.introText}>
              Вітаємо вас на платформі KMA Vote! Тут ви зможете взяти участь у
              політичному житті нашого університету та приймати важливі рішення.
            </p>
            <p className={styles.introText}>
              Для того, щоб переглянути доступні вам голосування, ввійдіть до
              вашого акаунта через Microsoft Office 365.
            </p>
            <div className={styles.introButtonContainer}>
              <LinkButton href={`${process.env.DOMAIN}/auth/ukma`} large>
                Ввійти з Microsoft Office
              </LinkButton>
            </div>
          </div>
        </main>
      </div>
    </Layout>
  );
};

export default Home;

export async function getStaticProps() {
  return {
    props: {
      protected: false,
      root: true,
    },
  };
}
